# Generated by Django 5.0.3 on 2024-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_remove_cohort_name_cohort_cohort_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
