# Generated by Django 5.0.3 on 2024-04-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_remove_cohort_name_cohort_cohort_code_and_more'),
        ('user_app', '0004_userdetail_delete_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cohort',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cohort_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohort.cohort', to_field='cohort_name'),
        ),
    ]
