# Generated by Django 5.0.3 on 2024-04-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_useraccount_cohort_useraccount_cohort_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
