# Generated by Django 5.0.3 on 2024-04-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_userdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
    ]
