# Generated by Django 5.0.3 on 2024-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=250)),
                ('repo_name', models.CharField()),
            ],
        ),
    ]
